name: CI

on:
  push:
    branches: [master, nightly]
  pull_request:
    branches: [master, nightly]
  workflow_dispatch:

jobs:
  curl-installation:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        jdk: [17]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.jdk }}
    - name: Install
      run: |
        bash ./install.sh
    - name: Test symlink
      run: ~/.local/bin/jdtls --version
    - name: Ensure runs
      run: |
        ~/.local/bin/jdtls &  # Execute in background
        sleep 5  # Wait for it to start
        kill $!  # If it succeeded, we should be able to kill it
