name: Test curl installer

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  installation:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        jdk: [17]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.jdk }}
    - name: Install
      run: curl -s https://raw.githubusercontent.com/eruizc-dev/jdtls-launcher/master/install.sh | bash
    - name: Test symlink
      run: ~/.local/bin/jdtls --version
    - name: Ensure runs
      run: |
        ~/.local/bin/jdtls &  # Execute in background
        sleep 5  # Wait for it to start
        kill $!  # If it succeeded, we should be able to kill it
