name: Test curl installer

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  installation-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
    - name: Install
      run: curl -s https://raw.githubusercontent.com/eruizc-dev/jdtls-launcher/master/install.sh | bash
    - name: Test symlink
      run: ~/.local/bin/jdtls --version
    - name: Ensure runs
      run: |
        ~/.local/bin/jdtls &  # Execute in background
        sleep 5  # Wait for it to start
        kill $!  # If it succeeded, we should be able to kill it

  installation-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
    - name: Install
      run: curl -s https://raw.githubusercontent.com/eruizc-dev/jdtls-launcher/master/install.sh | bash
    - name: Test symlink
      run: ~/.local/bin/jdtls --version
    - name: Ensure runs
      run: |
        ~/.local/bin/jdtls &  # Execute in background
        sleep 5  # Wait for it to start
        kill $!  # If it succeeded, we should be able to kill it

